# Generated by Django 3.0.3 on 2020-03-30 06:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('content_kg', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'информацию о нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHONE', 'Телефон'), ('FACEBOOK', 'Facebook'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'Whatsapp')], max_length=30, verbose_name='Тип контакта')),
                ('value', models.CharField(default='value', max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='CreditsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_kg', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('content_kg', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'информацию о кредитах',
                'verbose_name_plural': 'Информация о кредитах',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('content', models.TextField(verbose_name='Текст')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'обратную связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_kg', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_kg', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'информацию о истории успеха',
                'verbose_name_plural': 'История успеха',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('time', models.DateField(verbose_name='На какое время')),
                ('passport', models.FileField(upload_to='', verbose_name='Скан пасспорта')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('product', models.CharField(choices=[('Потребительский кредит', 'Потребительский кредит'), ('Агрокредит', 'Агрокредит'), ('Автокредит', 'Автокредит'), ('Кредит для развития бизнеса', 'Кредит для развития бизнеса'), ('Ипотека', 'Ипотека')], max_length=100, verbose_name='Продукт')),
                ('currency', models.CharField(choices=[('СОМ', 'Сом'), ('USD', 'USD')], max_length=30, verbose_name='Валюта')),
                ('other_credits', models.BooleanField(default=False, verbose_name='Есть ли другие кредиты?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заявку на кредит',
                'verbose_name_plural': 'Заявка на кредит',
                'ordering': ('-publish',),
            },
        ),
    ]
